config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests, only: [:new,:create] do
    member do
      post :approve
      post :deny
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ActiveRecord::Base
    CAT_COLORS = %w(black white orange gray)
    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :color, inclusion: CAT_COLORS
    validates :sex, inclusion: %w(M F)

    has_many :cat_rental_requests, dependent: :destroy
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
    RENTAL_STATUS = %w(PENDING APPROVED DENIED)
    validates :cat_id,:start_date,:end_date,:status,presence: true
    validates :status, inclusion: RENTAL_STATUS
    validate :does_not_overlap_approved_request

    belongs_to :cat

    def approve!
        raise "The request is not pending" unless self.status == 'PENDING'
        transaction do
            self.status = 'APPROVED'
            self.save!
            overlapping_pending_requests.each do |req|
                req.update!(status: 'DENIED')
            end
        end
    end

    def pending?
        self.status == 'PENDING'
    end

    def deny!
        self.status = 'DENIED'
        self.save!
    end

    def overlapping_requests
        CatRentalRequest
        .where.not(id: self.id)
        .where(cat_id: self.cat_id)
        .where.not('start_date > :end_date OR end_date < :start_date',start_date: start_date,end_date: end_date)
    end

    def overlapping_approved_requests
        overlapping_requests.where('status = \'APROVED\'')
    end

    def overlapping_pending_requests
        overlapping_requests.where('status = \'PENDING\'')
    end

    def does_not_overlap_approved_request
        unless overlapping_approved_requests.empty?
            errors[:base] <<
                "Request conflict with other exciting approved request"
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def approve
        current_cat_rental_request.approve!
        redirect_to cat_url(current_cat_rental_request.cat)
    end

    def deny
        current_cat_rental_request.deny!
        redirect_to cat_url(current_cat_rental_request.cat)
    end

    def new
        render :new
    end
    
    
    def create
        @cat_rental_request = CatRentalRequest.new(safe_params)
        if @cat_rental_request.save
            redirect_to cat_url(@cat_rental_request.cat)
        else  
            render :new
        end
    end 

    private 

    def current_cat_rental_request
        @cat_rental_request ||=
          CatRentalRequest.includes(:cat).find(params[:id])
    end

    def safe_params
        params.require(:cat_rental_request)
        .permit(:cat_id,:start_date,:end_date,:status)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all 
        render :index
    end

    def show 
        @cat = Cat.find(params[:id])
        render :show
    end

    def new 
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else 
            render :new
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit 
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date,:color,:name,:sex,:description)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create a new request</h1>

<form action="<%=cat_rental_requests_url%>" method="POST">
    <label for="cat_id">Cat Name : </label>
    <select name="cat_rental_request[cat_id]" id="cat_id">
        <option disabled selected> -- Choose the name of the cat -- </option>
        <% Cat.all.each do |cat| %>
        <option value="<%=cat.id%>"><%= cat.name %></option>
        <% end %>
    </select>
    
    <br><br>
    
    <label for="start_date">Start Date : </label>
    <input type="date" name="cat_rental_request[start_date]" id="start_date">
    <br><br>

    <label for="end_date">End Date : </label>
    <input type="date" name="cat_rental_request[end_date]" id="end_date">
    <br><br>
    <input type="submit" value="Create request">
</form>

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url )%>
<% method = (cat.persisted? ? "PATCH" : "POST" )%>
<% button_text = (cat.persisted? ? 'Update Cat Info' : 'Create Cat' )%>

<form action=<%=action%> method="POST">
    <input type="hidden" name="_method" value=<%=method%>>
    <label for="name">Name : </label>
    <input type="text" id ="name" name="cat[name]" value= "<%=cat.name%>">
    <br>
    <br>
    <input type="radio" id ="sex_m" name="cat[sex]" value="M" <%="checked" if cat.sex == "M"%>>
    <label for="sex_m">Male</label>
    <input type="radio" id ="sex_f" name="cat[sex]" value="F" <%="checked" if cat.sex == "F"%>>
    <label for="sex_f">Female</label>
    <br>
    <br>
    <label for="color">Color : </label>
    <select name="cat[color]" id = "color">
        <option disabled <%=cat.color ? "" : "selected"%>> -- Chose a color -- </option>
        <% Cat::CAT_COLORS.each do |color| %>
        <option value = "<%=color%>" <%="selected" if cat.color == color%>><%=color%></option>
        <% end %>
    </select>
    <br><br>
    <label for="date">Date : </label>
    <input type="date" id="date" name = "cat[birth_date]" value = "<%=cat.birth_date%>">
    <br><br>
    <label for="description">Description : </label>
    <input type="textarea" id="description" name="cat[description]" value= "<%=cat.description%>">
    <br><br>

    <input type="submit" value="<%=button_text%>">

</form>

app/views/cats/edit.html.erb
<h1>Creating a new cat</h1>

<%= render 'form', cat: @cat %>
<br>
<a href="<%=cats_url%>">Back to cats list</a>

app/views/cats/index.html.erb
<h1>List of Cats</h1>

<ul>
<% @cats.each do |cat| %>
<li><a href="<%= cat_url(cat)%>"><%= cat.name %></a></li>
<% end %>
</ul>
<a href="<%= new_cat_url()%>">Create a new cat</a>
<br>
<a href="<%= new_cat_rental_request_url%>">Rent a cat</a>

app/views/cats/new.html.erb
<h1>Creating a new cat</h1>

<%= render 'form', cat: @cat %>
<br>
<a href="<%=cats_url%>">Back to cats list</a>

app/views/cats/show.html.erb
<h1><%= @cat.name %> </h1>

<table>
    <% @cat.attributes.each do |name,value| %>
    <tr>
        <th><%= name %></th>
        <td><%= value %></td>
    </tr>
    <% end %>
</table>
<br>
<a href="<%=edit_cat_url(@cat)%>">Edit Cat</a>
<br>
<a href="<%= cats_url()%>"> Cats List</a>

<br><br>

<h2>Rental Requests</h2>
<table>
    <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
    </tr>
        <% @cat.cat_rental_requests.order('start_date').each do |req| %>
    <tr>
            <td><%= req.start_date %></td>
            <td><%= req.end_date %></td>
            <td>
            <% if req.pending? %>
        <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Approve">
        </form>
        <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Deny">
        </form>
        <% else %>
          <%= req.status %>
        <% end %>
        </td>
    </tr>
        <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NineNineCat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>